### ISSUE TITLE
Add esm and cjs libs

### ISSUE THREAD

**Issue by domlen2003** [UziTech/marked-katex-extension#113]
Currently (when building a project with vite - SvelteKit) i have to import the extension this way:
```js
import markedKatex from "marked-katex-extension/src/index";
```

This could be resolved by adding libs files for esm syntax (and common js syntax)

**Comment by UziTech** [comment]
Check if v2 works for you. I added cjs build. I've never used SvelteKit so I don't know how it works but the regular import should be the esm source.
