### ISSUE TITLE
ending $ followed by a - 

### ISSUE THREAD

**Issue by marc-polizzi** [UziTech/marked-katex-extension#201]
Improving the #193, would it be possible to add the `-` character as authorized after the trailing `$` character ?

For example, this one does not work without adding an extra space:

`$n$-vector`

Currently works:

`$n$ -vector`

Ty.

**Comment by UziTech** [comment]
If that is part of the equation wouldn't it be better to include it in the xatex like `$\text{$x$-vector}$`?

**Comment by marc-polizzi** [comment]
@UziTech yes that would do it ;-) 

Is there any reason not adding the `-` character as authorized after the trailing `$` character ?

**Comment by UziTech** [comment]
Ya then katex like I showed would not work.
