### ISSUE TITLE
Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by wtto00** [UziTech/marked-katex-extension#211]
Error reported on older versions of Safari: 
```
Invalid regular expression: invalid group specifier name
```
This is due to the [bug](https://bugs.webkit.org/show_bug.cgi?id=174931) in Safari.
I tested it on iOS 13.

Version 2.1.0 has no issues, while version 3.0.3 will throw an error.

**Comment by UziTech** [comment]
We only support the latest browsers. If you need to support an older browser you can use an older version.
