### ISSUE TITLE
Issues with rendering code blocks that have a `$` on their first line

### ISSUE THREAD

**Issue by sebastinez** [UziTech/marked-katex-extension#250]
It seems like when using `marked` without `marked-katex` a text like 
```
Check the README:
\```
$ cat README
Hello World!
\```
```
(don't mind the backslash)

is being rendered as intended, but with `marked-katex`, it is required to have at least two line breaks to make it work as intended.

Reproduction
https://svelte.dev/repl/c3a34f8ff6604397b70c3632624e54c5?version=4.2.1

**Comment by sebastinez** [comment]
Ok it seems this has to do with the `inlineStartRule` https://github.com/UziTech/marked-katex-extension/blob/78adfe944fd9d035f4d3d30693446b303caef3c1/src/index.js#L3

I'm by far no regex enthusiast but I was able with a negative look behind to make sure there aren't any backticks that represent a codeblock.

```diff
diff --git a/src/index.js b/src/index.js
index aad99ae..c859591 100644
--- a/src/index.js
+++ b/src/index.js
@@ -1,6 +1,6 @@
 import katex from 'katex';
 
-const inlineStartRule = /(\s|^)\${1,2}(?!\$)/;
+const inlineStartRule = /(?<!`)(\s|^)\${1,2}(?!\$)/;
 const inlineRule = /^(\${1,2})(?!\$)((?:\\.|[^\\\n])*?(?:\\.|[^\\\n\$]))\1(?=[\s?!\.,:]|$)/;
 const blockRule = /^(\${1,2})\n((?:\\[^]|[^\\])+?)\n\1(?:\n|$)/;

```

Eventually there is a better way, to keep the support for Safari, with avoiding negative look behinds

**Comment by UziTech** [comment]
First thing, there is supposed to be a blank line between markdown blocks. So this only affects markdown that is not well formatted. Second, it seems like this will be an issue for any inline extension inside a code block so this should probably be something that is fixed in marked.

**Comment by sebastinez** [comment]
Hey @UziTech thanks for your response.

So I agree on the first point, but [while marked handles it with grace](https://marked.js.org/demo/?text=Let's%20have%20a%20look%20at%20what%20the%20command%20did.%20Navigate%20to%20the%20working%20copy:%0A%0A%60%60%60%0A$%20cd%20heartwood%0A%60%60%60%0A%0ACheck%20the%20README:%0A%60%60%60%0A$%20cat%20README%0AHello%20World!%0A%60%60%60&options=%7B%0A%20%22async%22:%20false,%0A%20%22baseUrl%22:%20null,%0A%20%22breaks%22:%20false,%0A%20%22extensions%22:%20null,%0A%20%22gfm%22:%20false,%0A%20%22headerIds%22:%20true,%0A%20%22headerPrefix%22:%20%22%22,%0A%20%22highlight%22:%20null,%0A%20%22hooks%22:%20null,%0A%20%22langPrefix%22:%20%22language-%22,%0A%20%22mangle%22:%20true,%0A%20%22pedantic%22:%20false,%0A%20%22sanitize%22:%20false,%0A%20%22sanitizer%22:%20null,%0A%20%22silent%22:%20false,%0A%20%22smartypants%22:%20false,%0A%20%22tokenizer%22:%20null,%0A%20%22walkTokens%22:%20null,%0A%20%22xhtml%22:%20false%0A%7D&version=master)

`marked-katex` `blockKatex` extension seems to be too eager with the start detection beeing
https://github.com/UziTech/marked-katex-extension/blob/78adfe944fd9d035f4d3d30693446b303caef3c1/src/index.js#L56

Which seems to remove an existing line break, wouldn't it be possible to make the `blockKatex` start detection a bit more strict?

**Comment by UziTech** [comment]
We could require a blank line before the block katex to enforce the well formatted rule. Something like `src.indexOf('\n\s*\n$')`

**Comment by UziTech** [comment]
Really just removing the start function for block katex should work as well. That will only match katex at the start of a new block.

**Comment by sebastinez** [comment]
I'm ok with either one of them, AFAIK keeping the start function helps to filter out text before running it against the tokenizer function? So maybe enforcing the well formatted rule makes more sense?

**Comment by sebastinez** [comment]
Thank you very much @UziTech for the quick solution! 🙏
