### ISSUE TITLE
Hope to add Chinese punctuation in the punctuation after $

### ISSUE THREAD

**Issue by CreatorMC** [UziTech/marked-katex-extension#268]
I am a developer from China and I saw issue #193 

I am struggling with supporting latex in markdown, and this repository has been very helpful to me. However, just like #193 , I encountered the same problem with Chinese punctuation.

So, I hope to change the regular expression to this.
`/^(\${1,2})(?!\$)((?:\\.|[^\\\n])*?(?:\\.|[^\\\n\$]))\1(?=[\s?!\.,:？！。，：]|$)/`

My English proficiency is not good. If there are any mistakes, please forgive me.

**Comment by UziTech** [comment]
Ya if you can create a PR I can merge it

**Comment by CreatorMC** [comment]
> Ya if you can create a PR I can merge it

Thank you very much. I have submitted a PR.
