### ISSUE TITLE
How to displaying Chemical Formulas Correctly with Vue3 and Katex using marked-katex-extension

### ISSUE THREAD

**Issue by jiaopengzi** [UziTech/marked-katex-extension#315]
```vue
<!-- App.vue -->
<template>
  <div>vue3 import is not displayed correctly</div>
  <div v-html="ceFormat"></div>
</template>

<script lang="ts" setup>
import 'katex/dist/contrib/mhchem.min.js' // how use this
import 'katex/dist/katex.min.css' // katex css
import katex from 'katex'

const ceStr = `\\ce{N2 + 3H2 <=>T[High temperature Pressurized][Catalyst] 2NH3}`
const ceFormat = katex.renderToString(
  ceStr,
  {
    throwOnError: false,
    strict: 'warn',
  })
</script>
```

```html
<!-- app.html -->
<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
    />
    <script
    defer
      src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"
    ></script>
    <script
    defer
      src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/mhchem.min.js"
    ></script>
    <script
    defer
      src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"
      onload="renderMathInElement(document.body);"
    ></script>
  </head>
  <body>
    <p>
      html direct quote displays correctly
      <span class="katex-display">
        $$\ce{N2 + 3H2 <=>T[High temperature Pressurized][Catalyst] 2NH3}$$
      </span>
</html>

```

Hello,

I hope you don't mind me raising an issue.

I encountered some problems when using `vue3` and `katex` to render chemical formulas. They are not displaying properly.

The aforementioned chemical formulas can be displayed correctly when directly referenced in HTML.

![image](https://github.com/UziTech/marked-katex-extension/assets/52224629/2792f6fc-6ebe-49ba-9247-32da710a979e)

Could you please guide me on how to modify the code for vue3 when using your plugin `marked-katex-extension` to display chemical formulas correctly?

It seems that I need to use `KatexOptions` with `macros`, but I couldn't find suitable documentation to implement it. Any guidance would be greatly appreciated.

Thank you so much.

For reference on chemical formulas:

https://katex.org/docs/libs

https://github.com/KaTeX/KaTeX/tree/main/contrib/mhchem

**Comment by UziTech** [comment]
I have never used vue3, sorry. I can only tell you how to use the katex extension in marked by restating everything that is in the [readme](https://github.com/UziTech/marked-katex-extension).

You will need to figure out how to use marked with vue3 somewhere else.

**Comment by jiaopengzi** [comment]
```javascript
/**
 * @FilePath     index.js
 */
import { marked } from 'marked'
import markedKatex from 'marked-katex-extension'

marked.use(markedKatex({
  throwOnError: false,
  strict: 'warn',
}))

const ceMarkdown = `$$\\ce{N2 + 3H2 <=>T[High temperature Pressurized][Catalyst] 2NH3}$$`
const html = marked.parse(ceMarkdown)
console.log(html)

```

Excuse me, it was my mistake for not asking the question properly, and it is not related to Vue.

I have revisited the aforementioned `index.js` file, and when executed, the output is shown as in the provided image:
![image](https://github.com/UziTech/marked-katex-extension/assets/52224629/6d97062e-96a8-4c90-89af-1c98f1cd126d)



When I mentioned the HTML file before, adding 'https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/mhchem.min.js' would correctly display the result as shown in the following image:
![image](https://github.com/UziTech/marked-katex-extension/assets/52224629/e688fda2-2a23-4d97-be29-d540f7085ff6)



**The problem seems to be how to correctly reference `/katex/dist/contrib/mhchem.min.js` within the `marked-katex-extension`.**



Please kindly guide me on this matter. I truly appreciate your help.

**Comment by UziTech** [comment]
According to the katex [docs ](https://katex.org/docs/node#using-mhchem-extension)you should be able to just import the `mhchem` file.

```js
/**
 * @FilePath     index.js
 */
import { marked } from 'marked'
import markedKatex from 'marked-katex-extension'
import 'katex/contrib/mhchem'

marked.use(markedKatex({
  throwOnError: false,
  strict: 'warn',
}))

const ceMarkdown = `$$\\ce{N2 + 3H2 <=>T[High temperature Pressurized][Catalyst] 2NH3}$$`
const html = marked.parse(ceMarkdown)
console.log(html)
```

**Comment by jiaopengzi** [comment]
```html
<!-- use marked  -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Marked in the browser</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/mhchem.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/marked-katex-extension/lib/index.umd.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  </head>
  <body>
    <div id="content"></div>

    <script>
      const options = {
        throwOnError: false,
      }

      marked.use(markedKatex(options))
      document.getElementById('content').innerHTML = marked.parse(
        '$$\\ce{N2 + 3H2 <=>T[High temperature Pressurized][Catalyst] 2NH3}$$'
      )
    </script>
  </body>
</html>

```

```html
<!-- only use katex -->
<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
    />
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"
    ></script>
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/mhchem.min.js"
    ></script>
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"
      onload="renderMathInElement(document.body);"
    ></script>
  </head>
  <body>
    <span>
      $$\ce{N2 + 3H2 <=>T[High temperature Pressurized][Catalyst] 2NH3}$$
    </span>
  </body>
</html>

```



Once again, I would like to express my gratitude to you. I have also read the documentation you mentioned and tried to follow your approach for referencing, but unfortunately, it didn't work.

I'm not sure what details I might have missed. Could you please help me take another look?



- only use katex is ok
- use marked is not ok

**Comment by UziTech** [comment]
I have not tried using mhchem with this extension. It is possible that it won't work. If you get it working and want to create a PR, that would be awesome 😁👍. 

Unfortunately I don't think I can be of any additional help. You can try to pose this question in the katex repo to see if they have any insight.

**Comment by UziTech** [comment]
This does work when using marked with node. I don't know why the script tag doesn't work. Maybe using katex as a peer dependency would make it work.

```js
import { Marked } from 'marked';
import markedKatex from 'marked-katex-extension';
import 'katex/contrib/mhchem';
import { writeFileSync } from 'node:fs';

const marked = new Marked(markedKatex(), { breaks: true });

const markdown = `
$$\\ce{N2 + 3H2 <=>T[High temperature Pressurized][Catalyst] 2NH3}$$
`;
const body = marked.parse(markdown);

const html = `
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css" crossorigin="anonymous">
</head>
<body>
  ${body}
</body>
</html>
`;

writeFileSync('index.html', html, { encoding: 'utf-8' });
```

**Comment by UziTech** [comment]
I have comfirmed that the issue is that katex is included in the extension. Adding the mhchem extension extends the global katex but not the katex object inside the extension.

If we change katex to an external dependency we can allow the extensions.

This will have to be a breaking change.

**Comment by jiaopengzi** [comment]
That's fantastic, this issue has been troubling me for days. I really appreciate your guidance and assistance. I look forward to the new version. Thank you so much.

**Comment by jiaopengzi** [comment]
Hi, @UziTech 

I noticed your new PR for the above issue. When can we expect to use the updated extension?

Thanks in advance for your hard work!
