### ISSUE TITLE
Matrix do not display properly when 2x2

### ISSUE THREAD

**Issue by weiyuanC** [UziTech/marked-katex-extension#376]
Using marked and marked-katex-extension in a React application

Input:
$\mathbf{P} = \begin{pmatrix} 3 & 1 \\ 2 & 4  \end{pmatrix} $

Output:
![image](https://github.com/UziTech/marked-katex-extension/assets/25395979/e1d09cb5-4b78-410b-a3cf-ad8e375475bc)

The bracket does not cover the whole matrix. What might be the cause of it?

**Comment by UziTech** [comment]
This repo is only for the marked extension that uses katex for rendering.

You should ask this question on the [katex](https://github.com/KaTeX/KaTeX) repo.
