### ISSUE TITLE
Would it be better to mention the CSS import in the README.md file?

### ISSUE THREAD

**Issue by digitao-io** [UziTech/marked-katex-extension#419]
First of all, thanks a lot for making this extension! That's a great work what you have done! 😺👍

However there was a small unclarity in the documentation, which could be improved, IMHO.

At first I was trying out the extension, but it kept rendering the formular doubled, with both MathML and HTML ouput broken. I inspected it, and then I noticed that there is no styles being applied to the outputs.

Then I have tried:

```js
import "katex/dist/katex.min.css";
```

Everything works like a charm.

And then I have noticed that there is a sentence in the README.md file, mentioning that I have to add the CSS file in the HTML file.

Would it better to also mention the CSS import in the README.md file? Since nowadays, most people are using the bundlers, and this is probably the easiest way to apply the CSS file in the code.

**Comment by UziTech** [comment]
Sure, if you want to create a PR with the change we could add it
