### ISSUE TITLE
Issue with Matching Inline Matrix Formulas

### ISSUE THREAD

**Issue by AliaSabur** [UziTech/marked-katex-extension#420]
Hello,

Thank you for creating this extension—it’s impressive work!

I’ve noticed that the plugin struggles to match inline matrix formulas when text is present on the same line. For example:

```latex
test matrix $\left( \begin{matrix}
    1& 0& 0\\
    0& 1& 0\\
    0& 0& 1\\
\end{matrix}\right)$
```

Would it be possible to address this issue?

Thank you!

**Comment by UziTech** [comment]
The inline katex doesn't allow newlines. 

If the matrix needs to be inline you can include the text in the katex like:

```
$
\text{test matrix} \left( \begin{matrix}
    1& 0& 0\\
    0& 1& 0\\
    0& 0& 1\\

\end{matrix}\right)
$
```

If you want to create a PR to allow newlines in inline blocks I think it could work. There may still be edge cases that work in block katex but not inline katex, like blank lines. I haven't ran into a situation where I needed multi line inline katex yet.
