### ISSUE TITLE
support delimiters like \( ,  \) , \[ , \]

### ISSUE THREAD

**Issue by Leon406** [UziTech/marked-katex-extension#434]
It only supports $ and $$ 
	
Reference  https://katex.org/docs/autorender

**Comment by UziTech** [comment]
Those characters mean other things in markdown so we would have edge cases where the right thing to do wouldn't be obvious. 

If you would like to create your own extension that supports those feel free to copy any code from this extension.

**Comment by Leon406** [comment]
Got it.
I find solution from https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/components/markdown.tsx

**Comment by ShaunDychko** [comment]
The key function from https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/components/markdown.tsx is the following, which transforms, for example, \( x^2 \) to $ x^2 $.
```js
function escapeBrackets(text: string) {
  const pattern =
    /(```[\s\S]*?```|`.*?`)|\\\[([\s\S]*?[^\\])\\\]|\\\((.*?)\\\)/g;
  return text.replace(
    pattern,
    (match, codeBlock, squareBracket, roundBracket) => {
      if (codeBlock) {
        return codeBlock;
      } else if (squareBracket) {
        return `$$${squareBracket}$$`;
      } else if (roundBracket) {
        return `$${roundBracket}$`;
      }
      return match;
    },
  );
}
```
