### ISSUE TITLE
i can show ``` $$\left\{ x  \right.$$ ```, but ``` \[\left\{ x  \right.\] ``` will not show, I'm wondering why?

### ISSUE THREAD

**Issue by ericjiajia** [UziTech/marked-katex-extension#471]
i can show ``` $$\left\{ x  \right.$$ ```, but ``` \[\left\{ x  \right.\] ``` will not show, I'm wondering why?

i have already used katex/contrib/auto-render：
![image](https://github.com/user-attachments/assets/b5a5ba3f-4411-416d-a748-2d5e39eb319f)

others ``` \[ ... \] ``` will be show correctly

**Comment by UziTech** [comment]
It looks like you are rendering katex after running through marked. Do you have a repo where we can see the code and try to help?

**Comment by ericjiajia** [comment]
> It looks like you are rendering katex after running through marked. Do you have a repo where we can see the code and try to help?

sure i will make a demo repo for u later，thanks a lot

**Comment by ericjiajia** [comment]
> It looks like you are rendering katex after running through marked. Do you have a repo where we can see the code and try to help?

hello dude，this is our katex demo repo link：[https://github.com/xinla/katex-test](url)

it uses VUE3 and node 18.20.4，u can use ```  pnpm run dev``` to start the project. and u will see latex examples in lines 25, 27, and 29 of App.vue in the project.

Lines 25 and 29 use the same identifier. Lines 27 and 29 use the same latex formula, but the identifiers are inconsistent. However, lines 25 and 27 can be rendered, regardless of line 29. Cannot be rendered in any way

![image](https://github.com/user-attachments/assets/e0408306-4ed8-4c20-a386-bf4cf7df7999)

Looking forward to reply~

**Comment by UziTech** [comment]
What does the `renderMathInElement` function do? the `tempContent` should be rendered to html by the `marked.parse` call but that is not valid katex since the extension requires `$$` or `$` as a delimiter. You aren't sending the `autoRendererOptions` to marked at all so it has no way of knowing that `\\[ \\]` should be a delimiter.

**Comment by UziTech** [comment]
Also marked-katex-extension only allows `$` and `$$` as delimiters. If you would like other delimiters you can create your own extension.

You can copy most of this extension and just change the things you need to get it to work. I will warn you that using `[ ]` as delimiters is probably going to be harder than you think because they have special meaning in markdown for links and images.

**Comment by ericjiajia** [comment]
> What does the `renderMathInElement` function do? the `tempContent` should be rendered to html by the `marked.parse` call but that is not valid katex since the extension requires `$$` or `$` as a delimiter. You aren't sending the `autoRendererOptions` to marked at all so it has no way of knowing that `\\[ \\]` should be a delimiter.

this is what [renderMathInElement](https://github.com/UziTech/marked-katex-extension/issues/471#issuecomment-2519130050)do, it can be used to render latex formulas wrapped in `\\[ \\]`

If you say this, then I may think that this is not a problem with your library, but a problem with the katex autorender function.

you can try to ask chatgpt o1-preview:
```
\[
 \left\{\begin{array}{l}
 x - y = 2a, \\
 3x + y = 3a - 15.
 \end{array}\right.
 \]
 ```
Directly copy gpt's answer. The formula it answers is wrapped in `\[ \]`, Therefore, in some mathematical reasoning model applications, it is difficult to ensure that the algorithm returns a formula wrapped in `$`.

At the same time, I think I have temporarily found a solution. I modified the regular expression in your source code to support both `\[...\]` and `$$...$$` or support `\(. ..\)` and `$...$`. In my current testing, this problem seems to have been solved, but I am not sure what risks there may be in the future.

Like this:
```
const inlineRule = /^(?:\\\(([^]*?)\\\)|\$(?!\$)((?:\\.|[^\\\n])*?(?:\\.|[^\\\n\$]))\$)(?=[\s?!\.,:？！。，：]|$)/;
const inlineRuleNonStandard = /^(?:\\\(([^]*?)\\\)|\$(?!\$)((?:\\.|[^\\\n])*?(?:\\.|[^\\\n\$]))\$)/; 
const blockRule = /^(?:\\\[([^]*?)\\\]|\$\$((?:\\[^]|[^\\])+?)\$\$)(?:\n|$)/;
```

**Comment by jc-wow** [comment]
> > What does the `renderMathInElement` function do? the `tempContent` should be rendered to html by the `marked.parse` call but that is not valid katex since the extension requires `$$` or `$` as a delimiter. You aren't sending the `autoRendererOptions` to marked at all so it has no way of knowing that `\\[ \\]` should be a delimiter.
> 
> this is what [renderMathInElement](https://katex.org/docs/autorender.html) do, it can be used to render latex formulas wrapped in `\\[ \\]`
> 
> If you say this, then I may think that this is not a problem with your library, but a problem with the katex autorender function.
> 
> you can try to ask chatgpt o1-preview:
> 
> ```
> \[
> \left\{\begin{array}{l}
> x - y = 2a, \\
> 3x + y = 3a - 15.
> \end{array}\right.
> \]
> ```
> 
> Directly copy gpt's answer. The formula it answers is wrapped in `\[ \]`, Therefore, in some mathematical reasoning model applications, it is difficult to ensure that the algorithm returns a formula wrapped in `$`.
> 
> At the same time, I think I have temporarily found a solution. I modified the regular expression in your source code to support both `\[...\]` and `$$...$$` or support `\(. ..\)` and `$...$`. In my current testing, this problem seems to have been solved, but I am not sure what risks there may be in the future.
> 
> Like this:
> 
> ```
> const inlineRule = /^(?:\\\(([^]*?)\\\)|\$(?!\$)((?:\\.|[^\\\n])*?(?:\\.|[^\\\n\$]))\$)(?=[\s?!\.,:？！。，：]|$)/;
> const inlineRuleNonStandard = /^(?:\\\(([^]*?)\\\)|\$(?!\$)((?:\\.|[^\\\n])*?(?:\\.|[^\\\n\$]))\$)/; 
> const blockRule = /^(?:\\\[([^]*?)\\\]|\$\$((?:\\[^]|[^\\])+?)\$\$)(?:\n|$)/;
> ```

i'am finding ways to render formula inner a string like this, but failed to...
`斐波那契数列可以通过两种主要公式来表示：递归公式和显式公式（Binet公式）。\n\n### 递归公式：\n递归公式定义了斐波那契数列的每一项是前两项的和，具体如下：\n\\[\nF(n) =\n\\begin{cases}\n0, & \\text{if } n = 0, \\\\\n1, & \\text{if } n = 1, \\\\\nF(n-1) + F(n-2), & \\text{if } n > 1.\n\\end{cases}\n\\]\n\n### 显式公式（Binet公式）：\n斐波那契数列的第 \\(n\\) 项也可以通过显式公式计算（无需递归）：\n\\[\nF(n) = \\frac{\\phi^n - \\psi^n}{\\sqrt{5}},\n\\]\n其中：\n- \\(\\phi = \\frac{1 + \\sqrt{5}}{2}\\) 是黄金比例，\n- \\(\\psi = \\frac{1 - \\sqrt{5}}{2}\\) 是另一个根。\n\n**注意**：显式公式适用于任意 \\(n \\geq 0\\)，但可能需要取整来处理因浮点数误差导致的小数问题。`

**Comment by jc-wow** [comment]
> > What does the `renderMathInElement` function do? the `tempContent` should be rendered to html by the `marked.parse` call but that is not valid katex since the extension requires `$$` or `$` as a delimiter. You aren't sending the `autoRendererOptions` to marked at all so it has no way of knowing that `\\[ \\]` should be a delimiter.
> 
> this is what [renderMathInElement](https://katex.org/docs/autorender.html) do, it can be used to render latex formulas wrapped in `\\[ \\]`
> 
> If you say this, then I may think that this is not a problem with your library, but a problem with the katex autorender function.
> 
> you can try to ask chatgpt o1-preview:
> 
> ```
> \[
> \left\{\begin{array}{l}
> x - y = 2a, \\
> 3x + y = 3a - 15.
> \end{array}\right.
> \]
> ```
> 
> Directly copy gpt's answer. The formula it answers is wrapped in `\[ \]`, Therefore, in some mathematical reasoning model applications, it is difficult to ensure that the algorithm returns a formula wrapped in `$`.
> 
> At the same time, I think I have temporarily found a solution. I modified the regular expression in your source code to support both `\[...\]` and `$$...$$` or support `\(. ..\)` and `$...$`. In my current testing, this problem seems to have been solved, but I am not sure what risks there may be in the future.
> 
> Like this:
> 
> ```
> const inlineRule = /^(?:\\\(([^]*?)\\\)|\$(?!\$)((?:\\.|[^\\\n])*?(?:\\.|[^\\\n\$]))\$)(?=[\s?!\.,:？！。，：]|$)/;
> const inlineRuleNonStandard = /^(?:\\\(([^]*?)\\\)|\$(?!\$)((?:\\.|[^\\\n])*?(?:\\.|[^\\\n\$]))\$)/; 
> const blockRule = /^(?:\\\[([^]*?)\\\]|\$\$((?:\\[^]|[^\\])+?)\$\$)(?:\n|$)/;
> ```

i'am finding ways to render formula inner a string like this, but failed too...
斐波那契数列可以通过两种主要公式来表示：递归公式和显式公式（Binet公式）。\n\n### 递归公式：\n递归公式定义了斐波那契数列的每一项是前两项的和，具体如下：\n\\[\nF(n) =\n\\begin{cases}\n0, & \\text{if } n = 0, \\\\\n1, & \\text{if } n = 1, \\\\\nF(n-1) + F(n-2), & \\text{if } n > 1.\n\\end{cases}\n\\]\n\n### 显式公式（Binet公式）：\n斐波那契数列的第 \\(n\\) 项也可以通过显式公式计算（无需递归）：\n\\[\nF(n) = \\frac{\\phi^n - \\psi^n}{\\sqrt{5}},\n\\]\n其中：\n- \\(\\phi = \\frac{1 + \\sqrt{5}}{2}\\) 是黄金比例，\n- \\(\\psi = \\frac{1 - \\sqrt{5}}{2}\\) 是另一个根。\n\n**注意**：显式公式适用于任意 \\(n \\geq 0\\)，但可能需要取整来处理因浮点数误差导致的小数问题。

**Comment by UziTech** [comment]
Can you prompt chatgpt to output `$` and `$$` as delimiters instead? Or maybe even doing a `.replace(/\\\[/g, '$$')` before sending it to marked will be enough.
